# Generated by Django 4.2.3 on 2024-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user-avatar/', verbose_name='عکس کاربر'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_token',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='توکن'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_verify_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد تایید'),
        ),
    ]
