# Generated by Django 5.0.7 on 2024-08-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0003_rolemodel_userrolemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemodel',
            options={'verbose_name': 'نقش', 'verbose_name_plural': 'نقش ها'},
        ),
        migrations.AlterModelOptions(
            name='userrolemodel',
            options={'verbose_name': 'نقش کاربر', 'verbose_name_plural': 'نقش های کاربران'},
        ),
    ]
