# Generated by Django 5.0.7 on 2024-08-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0004_alter_rolemodel_options_alter_userrolemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
