# Generated by Django 5.0.7 on 2024-11-01 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0006_alter_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
