# Generated by Django 5.0.7 on 2024-11-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0007_tokenmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_token',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_verify_code',
        ),
    ]
