# Generated by Django 5.0.7 on 2024-11-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0008_remove_usermodel_user_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='userrolemodel',
            options={},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user-avatar/'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
