# Generated by Django 5.0.7 on 2024-11-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0010_otpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
