# Generated by Django 4.2.3 on 2024-08-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=150, verbose_name='عنوان دسته بندی')),
                ('category_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_title', models.CharField(max_length=150, verbose_name='عنوان زیر دسته')),
                ('sub_category_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در url')),
                ('sub_category_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Module.categorymodel', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'زیر دسته',
                'verbose_name_plural': 'زیر دسته ها',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150, verbose_name='نام کالا')),
                ('product_description', models.TextField(verbose_name='توضیحات کالا')),
                ('product_price', models.IntegerField(verbose_name='قیمت کالا')),
                ('product_create_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد محصول')),
                ('product_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در url')),
                ('product_discount', models.IntegerField(default=0, verbose_name='تخفیف کالا')),
                ('product_discount_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تخفیف کالا')),
                ('product_cover', models.ImageField(null=True, upload_to='product-cover/', verbose_name='عکس کالا')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Module.subcategorymodel', verbose_name='دسته یندی کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
        migrations.CreateModel(
            name='ProductImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='product-images/', verbose_name='عکس کالا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Module.productmodel', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'عکس کالا',
                'verbose_name_plural': 'عکس های کالا ها',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=150, verbose_name='نام ویژگی')),
                ('feature_description', models.CharField(max_length=150, verbose_name='توضیح ویژگی')),
                ('feature_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Module.productmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی کالا',
                'verbose_name_plural': 'ویژگی های کالا ها',
            },
        ),
    ]
