# Generated by Django 4.2.3 on 2024-08-03 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product_Module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='متن کامنت')),
                ('comment_rating', models.IntegerField(verbose_name='امتیاز')),
                ('comment_create_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('comment_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Module.productmodel', verbose_name='محصول')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
