# Generated by Django 5.0.7 on 2024-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0002_productcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_sale_count',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش کالا'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد کالا'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
