# Generated by Django 5.0.7 on 2024-08-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0004_productmodel_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='sub_category_slug',
            new_name='slug',
        ),
    ]
