# Generated by Django 5.0.7 on 2024-08-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0005_rename_sub_category_slug_subcategorymodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='slug',
            new_name='sub_category_slug',
        ),
    ]
