# Generated by Django 5.0.7 on 2024-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0006_rename_slug_subcategorymodel_sub_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_discount_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ تخفیف کالا'),
        ),
    ]
