# Generated by Django 5.0.7 on 2024-08-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0007_alter_productmodel_product_discount_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_count',
            field=models.IntegerField(default=0, verbose_name='تعداد محصول'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کالا'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_discount_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تخفیف کالا'),
        ),
    ]
