# Generated by Django 5.0.7 on 2024-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0008_productmodel_product_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('img', models.ImageField(upload_to='banner/', verbose_name='عکس')),
                ('url', models.CharField(max_length=1000, verbose_name='آدرس صفحه')),
            ],
        ),
    ]
