# Generated by Django 5.0.7 on 2024-10-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0009_homepagebannermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebannermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
