# Generated by Django 5.0.7 on 2024-10-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0010_homepagebannermodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagebannermodel',
            options={'verbose_name': 'بنر', 'verbose_name_plural': 'بنر ها'},
        ),
    ]
