# Generated by Django 5.0.7 on 2024-09-29 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Module', '0001_initial'),
        ('Product_Module', '0008_productmodel_product_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitemmodel',
            options={'verbose_name': 'محصول سبد خرید', 'verbose_name_plural': 'محصولات سبد های خرید'},
        ),
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید'},
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart_Module.cartmodel', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Module.productmodel', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
