# Generated by Django 5.0.7 on 2024-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0002_post_cover_img_alter_post_author_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='عنوان در url'),
        ),
    ]
